[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
indoc = "1.0.7"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[[bin]]
name = "day3"
path = "src/day3.rs"
